trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    echo "Listing files..."
    ls -la
  displayName: "Check files"

- script: |
    echo "Running app.js"
    node app.js
  displayName: "Run JavaScript"